{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1beta1" }}
apiVersion: networking.k8s.io/v1beta1
{{ else }}
apiVersion: extensions/v1beta1
{{ end -}}
kind: Ingress
metadata:
  name: {{ .Release.Namespace }}-forno-ingress
  labels:
{{ include "common.standard.labels" .  | indent 4 }}
    component: forno
  annotations:
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    # Allows WS connections to be 20 minutes long, see https://kubernetes.github.io/ingress-nginx/user-guide/miscellaneous/#websockets
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1200"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "1200"
spec:
  tls:
  - hosts:
    - {{ .Release.Namespace }}-forno.{{ .Values.domain.name }}.org
    secretName: {{ .Release.Namespace }}-forno-web-tls
  rules:
  - host: {{ .Release.Namespace }}-forno.{{ .Values.domain.name }}.org
    http:
      paths:
      - path: /
        backend:
          serviceName: tx-nodes
          servicePort: 8545
      - path: /ws
        backend:
          serviceName: tx-nodes
          servicePort: 8546
