geth:
  resources:
    requests:
      memory: "21Gi"
      cpu: "7"
  service_session_affinity: None
  node_keys:
  - "28406f9c37274e163f5f3335fec2a35e0d3bf3895c28f7a54dd8ecd614d1437c"
  - "7c0b1c0518bdd3e1a0db8b0ed6999e4404b344a950462fda42ab53ca7ccea271"
  - "e658b12507dc91948440e15dc5f85d670b9c55a6ec0ad6e11f87a2eacebf07c5"
  - "3d9a4d83ac67bef79558fe49993ac0436fa15a64b9d383a77c808d0653911722"
  - "eb8a93871d8ae965484e00d6381cd3756dc13381a98bf715456f0a7dd940ad9e"
  - "87d3a7ce70fc43db4a070a0db1b69ac78f8db0e10163e34248347966b3a8b072"
  - "e7565adbdfab09dab769148a34da35168ababecbba6a468d21ccd9fcff9b5946"
  - "09e2c8c304c5019c5569f27ceea3f1d6d97facbdf8fe410831cd3c615e5df82f"

extraPodLabels:
  stack: blockscout
  mode: archive
