fullnameOverride: rc1staging-archivenodes
gcp: true
genesis:
  network: rc1
  networkId: 42220
geth:
  gcmode: archive
  image:
    imagePullPolicy: IfNotPresent
    repository: us.gcr.io/celo-org/geth
    tag: 1.5.6
  light:
    maxpeers: 1000
    serve: 90
  maxpeers: 1100
  node_keys:
  - 5781152a2ab09ae18dd0a48baacc743c9b05f7542d6207615c86dd9bc21b5c94
  - 609a06841bbf4e7579ee804d9422094f2401d455b8834336a3faea3545950fa8
  public_ip_per_node: [] # needs to be provided
  resources:
    requests:
      cpu: "7"
      memory: 21Gi
  rpc_apis: eth,net,rpc,web3,txpool,debug
  service_type: None
  use_gstorage_data: false
  ws_port: 8545
  increase_timeouts: true
namespace: rc1staging
replicaCount: 2
storage:
  size: 1500Gi
  storageClass: ssd
extraPodLabels:
  stack: blockscout
  mode: archive
