annotations:
  # Enable Prometheus scraping of log based metrics,
  # see https://grafana.com/docs/loki/latest/clients/promtail/configuration/#pipeline_stages: metrics
  prometheus.io/scrape: 'true'
  prometheus.io/port: 'http-metrics'

config:
  # add a destination for the logs ingestion
  # lokiAddress:

  snippets:
    pipelineStages:
      - cri: {}
      - docker: {}

    extraRelabelConfigs:
    # Do not ingest logs for fluentd.
    - action: drop
      source_labels:
        - app
      regex: fluentd-log-agent
    # Keep Kubernetes pod labels.
    - action: labelmap
      regex: __meta_kubernetes_pod_label_(.+)
    # Only keep logs from these namespaces.
    - action: keep
      source_labels:
        - namespace
      # TODO: reconsider what should be kept from the default namespace
      # eg: ingress controller
      regex: (alfajores|baklava|default|komenci|rc1|rc1staging|staging|walletconnect)

serviceAccount:
  # add a iam.gke.io/gcp-service-account, see
  # https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity#gcloud
  annotations: {}

updateStrategy:
  type: RollingUpdate