{{ range $index, $e := until (int .Values.replicaCount ) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "common.fullname" $ }}-{{ $index }}
  annotations:
{{ if $.Values.azure }}
    service.beta.kubernetes.io/azure-load-balancer-mixed-protocols: "true"
{{ end }}
  labels:
{{ include "common.standard.labels" $ | indent 4 }}
    component: celo-fullnode-protocol-traffic
spec:
  type: {{ $.Values.geth.service_type }}
  publishNotReadyAddresses: true
{{- if (eq $.Values.geth.service_type "LoadBalancer") }}
  loadBalancerIP: {{ index $.Values.geth.public_ips $index -}}
{{- end }}
  ports:
{{- if $.Values.geth.service_node_port_per_full_node }}
{{- $port := index $.Values.geth.service_node_port_per_full_node $index }}
    - targetPort: {{ $port }}
      port: {{ $port }}
      nodePort: {{ $port }}
      name: tcp
      protocol: TCP
    - targetPort: {{ $port }}
      port: {{ $port }}
      nodePort: {{ $port }}
      name: udp
      protocol: UDP
{{- else }}
    - port: 30303
      targetPort: ethereum
      name: ethereum
{{- end }}
{{- if $.Values.geth.expose_rpc_externally }}
{{ include "celo-fullnode.rpc-ports" . | indent 4 }}
{{- end }}
  selector:
    statefulset.kubernetes.io/pod-name: {{ template "common.fullname" $ }}-{{ $index }}
---
{{ end }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "common.fullname" . }}-rpc
  labels:
{{ include "common.standard.labels" .  | indent 4 }}
  component: celo-fullnode-rpc-traffic
spec:
  type: ClusterIP
  ports:
{{ include "celo-fullnode.rpc-ports" . | indent 4 }}
  selector:
{{ include "common.standard.labels" .  | indent 4 }}
  component: celo-fullnode
