blockscout:
  indexer:
    db:
      connectionName: celo-testnet-production:us-west1:rc13
      proxy:
        resources:
          requests:
            memory: 4Gi
            cpu: 500m
    poolSize: 100
    resources:
      requests:
        memory: 12Gi
        cpu: 5
  api:
    autoscaling:
        maxReplicas: 5
        minReplicas: 2
        target:
          cpu: 70
    db:
      connectionName: celo-testnet-production:us-west1:rc13-replica
      proxy:
        resources:
          requests:
            memory: 500Mi
            cpu: 300m
    poolSize: 30
    resources:
      requests:
        memory: 500Mi
        cpu: 1500m
  web:
    host: explorer.celo.org
    autoscaling:
      maxReplicas: 5
      minReplicas: 2
      target:
        cpu: 70
    db:
      connectionName: celo-testnet-production:us-west1:rc13
      proxy:
        resources:
          requests:
            memory: 500Mi
            cpu: 300m
    poolSize: 30
    resources:
      requests:
        memory: 500Mi
        cpu: 1500m
    recaptchaSecretName: rc1-blockscout-recaptcha
    stats:
      enabled: true
      reportUrl: https://datastudio.google.com/embed/reporting/e0a253b1-fa37-43d0-bbc3-2706a64f2211/page/hDehC?hl=en
  metadataCrawler:
    enabled: true
    discordClusterName: Mainnet
  archiveNodes:
    jsonrpcHttpUrl: http://rc1-fullnodes-rpc-internal-lb:8545
    jsonrpcWsUrl: ws://rc1-fullnodes-rpc-internal-lb:8545
  metrics:
    enabled: true
  chain:
    subnetwork: Celo
    networkID: 42220
