blockscout:
  indexer:
    db:
      connectionName: celo-testnet-production:us-west1:rc11
      proxy:
        resources:
          requests:
            memory: 4Gi
            cpu: 500m
    poolSize: 100
    resources:
      requests:
        memory: 12Gi
        cpu: 5
  api:
    autoscaling:
        maxReplicas: 5
        minReplicas: 2
        target:
          cpu: 70
    db:
      connectionName: celo-testnet-production:us-west1:rc11-replica
      proxy:
        resources:
          requests:
            memory: 500Mi
            cpu: 300m
    poolSize: 30
    resources:
      requests:
        memory: 500Mi
        cpu: 1500m
  web:
    host: explorer.celo.org
    autoscaling:
      maxReplicas: 5
      minReplicas: 2
      target:
        cpu: 70
    db:
      connectionName: celo-testnet-production:us-west1:rc11
      proxy:
        resources:
          requests:
            memory: 500Mi
            cpu: 300m
    poolSize: 30
    resources:
      requests:
        memory: 500Mi
        cpu: 1500m
    stats:
      enabled: true
      reportUrl: '{"overview": "https://datastudio.google.com/embed/reporting/60bea1af-3e82-4eb0-a313-158582baa710/page/hDehC?hl=en", "addresses":"https://datastudio.google.com/embed/reporting/1e334bed-f7c9-4ee6-ac77-2c4cc3dae04c/page/hDehC?hl=en", "cStables":"https://datastudio.google.com/embed/reporting/28a3620e-e12d-41ea-b361-d44b82cbfeda/page/hDehC?hl=en", "transactions":"https://datastudio.google.com/embed/reporting/c5ecbd9b-d277-488f-8caf-4c8b64305e55/page/hDehC?hl=en", "reserve": "https://datastudio.google.com/embed/reporting/965b3c9f-6d36-4d45-818d-34d4f59d89dd/page/hDehC?hl=en"}'
      makerdojo: '{"attestations": "https://makerdojo.io/public/dashboards/DjNVIYqQiyxIEcTx3Io4IwQg7U56lqQPyrSYdnXl?embed=clabs","uniswap":"https://makerdojo.io/public/dashboards/1qUlHeb7W9jnPVuXv6yeRatEYxSXPDsFQUODR1bp?embed=clabs","moola":"https://makerdojo.io/public/dashboards/tWnDs1CsMQyaSLHFHj0MUoNz20WbxjGv72fCTxgq?embed=clabs"}'
  metadataCrawler:
    enabled: true
    discordClusterName: Mainnet
  archiveNodes:
    jsonrpcHttpUrl: http://rc1-fullnodes-rpc-internal-lb:8545
    jsonrpcWsUrl: ws://rc1-fullnodes-rpc-internal-lb:8545
  metrics:
    enabled: true
  fullNodes:
    jsonrpcPublicHttp: https://forno.celo.org
  secrets:
    segmentKey: gcp:secretmanager:projects/365081401101/secrets/rc1-blockscout-segmentKey
    discordWebhookUrl: gcp:secretmanager:projects/365081401101/secrets/rc1-blockscout-discordWebhookUrl
    dbUser: gcp:secretmanager:projects/365081401101/secrets/rc1-blockscout1-dbUser
    dbPassword: gcp:secretmanager:projects/365081401101/secrets/rc1-blockscout1-dbPassword
    dbUrl: gcp:secretmanager:projects/365081401101/secrets/rc1-blockscout1-dbUrl
    recaptcha:
      projectId: gcp:secretmanager:projects/365081401101/secrets/rc1-blockscout-recaptchaProjectId
      siteKey: gcp:secretmanager:projects/365081401101/secrets/rc1-blockscout-recaptchaSiteKey
      apiKey: gcp:secretmanager:projects/365081401101/secrets/rc1-blockscout-recaptchaApiKey
  chain:
    subnetwork: Celo
    networkID: 42220
