blockscout:
  indexer:
    db:
      connectionName: celo-testnet-production:us-west1:alfajores3
      proxy:
        resources:
          requests:
            memory: 250Mi
            cpu: 200m
    poolSize: 200
    resources:
      requests:
        memory: 700Mi
        cpu: 1500m
  api:
    autoscaling:
        maxReplicas: 3
        minReplicas: 2
        target:
          cpu: 70
    db:
      connectionName: celo-testnet-production:us-west1:alfajores3-replica
      proxy:
        resources:
          requests:
            memory: 250Mi
            cpu: 200m
    poolSize: 10
    resources:
      requests:
        memory: 250Mi
        cpu: 500m
  web:
    host: explorer.celo.org
    suffix:
      enabled: true
      path: "alfajores"
    autoscaling:
      maxReplicas: 3
      minReplicas: 2
      target:
        cpu: 70
    db:
      connectionName: celo-testnet-production:us-west1:alfajores3-replica
      proxy:
        resources:
          requests:
            memory: 250Mi
            cpu: 200m
    poolSize: 20
    resources:
      requests:
        memory: 250M
        cpu: 500m
  metadataCrawler:
    enabled: true
    schedule: "*/30 * * * *" # every 30 minutes
  metrics:
    enabled: true
  fullNodes:
    jsonrpcPublicHttp: https://alfajores-forno.celo-testnet.org
  secrets:
    segmentKey: gcp:secretmanager:projects/365081401101/secrets/alfajores-blockscout-segmentKey
    dbUser: gcp:secretmanager:projects/365081401101/secrets/alfajores-blockscout3-dbUser
    dbPassword: gcp:secretmanager:projects/365081401101/secrets/alfajores-blockscout3-dbPassword
    grafanaCloud: gcp:secretmanager:projects/365081401101/secrets/alfajores-blockscout-grafanaCloud
    recaptcha:
      projectId: gcp:secretmanager:projects/365081401101/secrets/alfajores-blockscout-recaptchaProjectId
      siteKey: gcp:secretmanager:projects/365081401101/secrets/alfajores-blockscout-recaptchaSiteKey
      apiKey: gcp:secretmanager:projects/365081401101/secrets/alfajores-blockscout-recaptchaApiKey
    erlang:
      cookie: gcp:secretmanager:projects/365081401101/secrets/alfajores-blockscout3-erlangCookie
    campaignBannerApiUrl: gcp:secretmanager:projects/365081401101/secrets/alfajores-blockscout-campaignBannerApiUrl
  chain:
    subnetwork: Alfajores
    networkID: 44787
