blockscout:
  indexer:
    db:
      connectionName: celo-testnet-production:us-west1:baklava2
      proxy:
        resources:
          requests:
            memory: 250Mi
            cpu: 200m
    poolSize: 30
    resources:
      requests:
        memory: 1000Mi
        cpu: 2
    metrics:
      enabled: true
  api:
    autoscaling:
        maxReplicas: 3
        minReplicas: 2
        target:
          cpu: 70
    db:
      connectionName: celo-testnet-production:us-west1:baklava2-replica
      proxy:
        resources:
          requests:
            memory: 250Mi
            cpu: 200m
    poolSize: 10
    resources:
      requests:
        memory: 250Mi
        cpu: 500m
  web:
    host: baklava-blockscout.celo-testnet.org
    autoscaling:
      maxReplicas: 3
      minReplicas: 2
      target:
        cpu: 70
    db:
      connectionName: celo-testnet-production:us-west1:baklava2
      proxy:
        resources:
          requests:
            memory: 250Mi
            cpu: 200m
    poolSize: 10
    resources:
      requests:
        memory: 250M
        cpu: 500m
  metadataCrawler:
    enabled: true
    schedule: "*/30 * * * *"
    discordClusterName: Baklava
  metrics:
    enabled: true
  secrets:
    segmentKey: gcp:secretmanager:projects/365081401101/secrets/baklava-blockscout-segmentKey
    dbUser: gcp:secretmanager:projects/365081401101/secrets/baklava-blockscout2-dbUser
    dbPassword: gcp:secretmanager:projects/365081401101/secrets/baklava-blockscout2-dbPassword
    dbUrl: gcp:secretmanager:projects/365081401101/secrets/baklava-blockscout2-dbUrl
    recaptcha:
      projectId: gcp:secretmanager:projects/365081401101/secrets/baklava-blockscout-recaptchaProjectId
      siteKey: gcp:secretmanager:projects/365081401101/secrets/baklava-blockscout-recaptchaSiteKey
      apiKey: gcp:secretmanager:projects/365081401101/secrets/baklava-blockscout-recaptchaApiKey
  chain:
    subnetwork: Baklava
    networkID: 62320
