apiVersion: v1
kind: Secret
metadata:
  name: prometheus-service-account-key
  labels:
    name: prometheus-service-account-key
    chart: prometheus-stackdriver
    release: prometheus-stackdriver
    heritage: prometheus-stackdriver
    component: prometheus-stackdriver
type: Opaque
data:
  prometheus-service-account.json: {{ .Values.gcloudServiceAccountKeyBase64 }}
