# This file is intended to show the expected value structure with placeholder values

environment:
  name: test

image:
  repository: oracletest.azurecr.io/test/oracle
  tag: hsmtest

kubectl:
  image:
    repository: bitnami/kubectl
    tag: 1.17.4

oracle:
  replicas: 2
  web3ProviderUrl: https://alfajoresstaging-forno.celo-testnet.org
  identities:
  - address: 0x0000000000000000000000000000000000000000
    azure:
      id: defaultId
      clientId: defaultClientId
      keyVaultName: defaultKeyVaultName
  - address: 0x0000000000000000000000000000000000000001
    azure:
      id: defaultId1
      clientId: defaultClientId1
      keyVaultName: defaultKeyVaultName1
  azureHsm:
    initTryCount: 5
    initMaxRetryBackoffMs: 30000
  metrics:
    enabled: true
    prometheusPort: 9090
