environment:
  name: test
  network: alfajores
  cluster:
    name: test-cluster
    location: location

walletconnect:
  image:
    repository: us.gcr.io/celo-testnet/walletconnect
    tag: 1472bcaad57e3746498f7a661c42ff5cf9acaf5a
    imagePullPolicy: IfNotPresent
  service:
    type: ClusterIP

domain:
  name: walletconnect

redis:
  cluster:
    enabled: false
  usePassword: false

ingressClassName: nginx
