apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Namespace }}-celostats-server
  labels:
    app: celostats
    chart: celostats
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: celostats-server
  annotations:
    kubernetes.io/tls-acme: "true"
spec:
  ingressClassName: {{ default "nginx" .Values.ingressClassName }}
  tls:
  - hosts:
    - {{ .Release.Namespace }}-celostats-server.{{ .Values.domain.name }}.org
    secretName: {{ .Release.Namespace }}-celostats-tls
  rules:
  - host: {{ .Release.Namespace }}-celostats-server.{{ .Values.domain.name }}.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Namespace }}-celostats-server
            port: 
              number: 80
