apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Namespace }}-ethstats-ingress
  labels:
    app: celostats
    chart: celostats
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: ethstats
  annotations:
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($http_upgrade != "websocket") {
        return 301 https://{{ .Release.Namespace }}-celostats.{{ .Values.domain.name }}.org/;
      }
spec:
  ingressClassName: {{ default "nginx" .Values.ingressClassName }}
  tls:
  - hosts:
    - {{ .Release.Namespace }}-ethstats.{{ .Values.domain.name }}.org
    secretName: {{ .Release.Namespace }}-ethstats-tls
  rules:
  - host: {{ .Release.Namespace }}-ethstats.{{ .Values.domain.name }}.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Namespace }}-celostats-server
            port: 
              number: 80
