apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "komenci-onboarding-fullname" . }}
  labels:
{{- include "komenci-onboarding-component-label" . | nindent 4 }}
spec:
  replicas: {{ .Values.onboarding.replicaCount }}
  selector:
    matchLabels: 
    {{- include "komenci-onboarding-component-label" . | nindent 6 }}
  template:
    metadata:
      labels:
{{- include "komenci-onboarding-component-label" . | nindent 8 }}
    spec:
      containers:
        - name: komenci-onboarding
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000
          command:
            - bash
            - "-c"
            - |
              node packages/apps/api/dist/main.js
          resources:
            {{- toYaml .Values.onboarding.resources | nindent 12 }}
          env:
          - name: REPLICA_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
{{ include "common.env-var" (dict "name" "RULE_SIGNATURE_ENABLED" "dict" .Values.onboarding.ruleEnabled "value_name" "signature") | indent 10 }}
{{ include "common.env-var" (dict "name" "RULE_CAPTCHA_ENABLED" "dict" .Values.onboarding.ruleEnabled "value_name" "captcha") | indent 10 }}
{{ include "common.env-var" (dict "name" "RULE_CAPTCHA_CONFIG_BYPASS_ENABLED" "dict" .Values.onboarding.ruleConfig.captcha "value_name" "bypassEnabled") | indent 10 }}
{{ include "common.env-var" (dict "name" "RULE_CAPTCHA_CONFIG_BYPASS_TOKEN" "dict" .Values.onboarding.ruleConfig.captcha "value_name" "bypassToken") | indent 10 }}
{{ include "common.env-var" (dict "name" "RECAPTCHA_TOKEN" "dict" .Values.onboarding "value_name" "recaptchaToken") | indent 10 }}
{{ include "common.env-var" (dict "name" "QUOTA_DISTRIBUTED_BLINDED_PEPPER" "dict" .Values.onboarding.quota "value_name" "distributedBlindePepper") | indent 10 }}
{{ include "common.env-var" (dict "name" "QUOTA_REQUEST_SUBSIDISED_ATTESTATION" "dict" .Values.onboarding.quota "value_name" "requestSubsidisedAttestation") | indent 10 }}
{{ include "common.env-var" (dict "name" "QUOTA_SUBMIT_META_TRANSACTION" "dict" .Values.onboarding.quota "value_name" "submitMetaTransaction") | indent 10 }}
{{ include "common.env-var" (dict "name" "DB_HOST" "dict" .Values.onboarding.db "value_name" "host" "optional" true) | indent 10 }}
{{ include "common.env-var" (dict "name" "DB_PORT" "dict" .Values.onboarding.db "value_name" "port" "optional" true) | indent 10 }}
{{ include "common.env-var" (dict "name" "DB_USERNAME" "dict" .Values.onboarding.db "value_name" "username") | indent 10 }}
{{ include "common.env-var" (dict "name" "DB_PASSWORD" "dict" .Values.onboarding.db "value_name" "password") | indent 10 }}
{{ include "common.env-var" (dict "name" "DB_DATABASE" "dict" .Values.onboarding.db "value_name" "database") | indent 10 }}
{{ include "common.env-var" (dict "name" "DB_SYNCHRONIZE" "dict" .Values.onboarding.db "value_name" "synchronize") | indent 10 }}
{{ include "common.env-var" (dict "name" "DB_SSL" "dict" .Values.onboarding.db "value_name" "ssl") | indent 10 }}
{{ include "common.env-var" (dict "name" "NODE_ENV" "dict" .Values.onboarding "value_name" "node_env") | indent 10 }}
{{ include "common.env-var" (dict "name" "RELAYER_HOST" "dict" .Values.onboarding.relayer "value_name" "host") | indent 10 }}
{{ include "common.env-var" (dict "name" "RELAYER_PORT" "dict" .Values.onboarding.relayer "value_name" "port") | indent 10 }}
{{ include "common.env-var" (dict "name" "RELAYER_RPC_TIMEOUT_MS" "dict" .Values.onboarding.relayer "value_name" "rpcTimeoutMs") | indent 10 }}
{{ include "common.env-var" (dict "name" "THROTTLE_TTL" "dict" .Values.onboarding.throttle "value_name" "ttl") | indent 10 }}
{{ include "common.env-var" (dict "name" "THROTTLE_LIMIT" "dict" .Values.onboarding.throttle "value_name" "limit") | indent 10 }}
{{ include "common.env-var" (dict "name" "NETWORK" "dict" .Values.environment "value_name" "network") | indent 10 }}
{{ include "common.env-var" (dict "name" "PUBLIC_URL" "dict" .Values.onboarding "value_name" "publicUrl") | indent 10 }}
          readinessProbe:
            httpGet:
              path: /v1/health
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 3
          livenessProbe:
            httpGet:
              path: /v1/health
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 10
      {{- with .Values.onboarding.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.onboarding.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.onboarding.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
