cluster: changeset

disableStackDriverMetrics: false

gcloud:
  project: celo-testnet
  region: us-west1-b
  # gceScrapeZones:
  # - "us-west1-a"
  # - "us-west1-b"
  # - "us-west1-c"

includeFilter: '{job=~".+",__name__!~"kube_.+_labels",__name__!~"apiserver_.+",__name__!~"kube_certificatesigningrequest_.+",__name__!~"kube_configmap_.+",__name__!~"kube_cronjob_.+",__name__!~"kube_endpoint_.+",__name__!~"kube_horizontalpodautoscaler_.+",__name__!~"kube_ingress_.+",__name__!~"kube_job_.+",__name__!~"kube_lease_.+",__name__!~"kube_limitrange_.+",__name__!~"kube_mutatingwebhookconfiguration_.+",__name__!~"kube_namespace_.+",__name__!~"kube_networkpolicy_.+",__name__!~"kube_poddisruptionbudget_.+",__name__!~"kube_replicaset_.+",__name__!~"kube_replicationcontroller_.+",__name__!~"kube_resourcequota_.+",__name__!~"kube_secret_.+",__name__!~"kube_service_.+",__name__!~"kube_storageclass_.+",__name__!~"kube_service_.+",__name__!~"kube_validatingwebhookconfiguration_.+",__name__!~"kube_verticalpodautoscaler_.+",__name__!~"kube_volumeattachment_.+",__name__!~"kubelet_.+",__name__!~"phoenix_.+",__name__!~"workqueue_.+"}'

namespace: prometheus

prometheus:
  imageTag: v2.17.0
  retention_time: 7d

sidecar:
  imageTag: 0.7.3

stackdriver_metrics_prefix: external.googleapis.com/prometheus/prefix

# storageClassName: ssd

storageSize: 50Gi

serviceAccount:
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

remote_write: {}
# - url: https://prometheus-us-central1.grafana.net/api/prom/push
#   basic_auth:
#     username: 51505
#     password: ey...
