apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-web-ingress
  labels:
    {{- include "celo.blockscout.labels" . | nindent 4 }}
    component: blockscout-web-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 8m
    {{- if .Values.blockscout.web.suffix.enabled }}
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    {{- end }}
    nginx.ingress.kubernetes.io/configuration-snippet: |
      {{- if .Values.blockscout.web.suffix.enabled }}
      location ~ ^/(?!({{ .Values.blockscout.web.suffix.path }})) {
        return 307 /{{ .Values.blockscout.web.suffix.path }}$request_uri;
      }
      {{- end }}
      location ~ /admin/.* {
        deny all;
      }
      location ~ /wobserver/.* {
        deny all;
      }
      location ~ /address/(.*)/token_transfers {
        return 301 /address/$1/token-transfers;
      }
      location ~ /address/(.*)/coin_balances {
        return 301 /address/$1/coin-balances;
      }
    {{- if .Values.blockscout.web.basicAuth.enabled }}
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: {{ .Release.Name }}-web-basic-auth
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
    {{- end }}
spec:
  ingressClassName: {{ default "nginx" .Values.ingressClassName }}
  tls:
  - hosts:
    - {{ .Release.Name }}.{{ .Values.blockscout.domainName }}
    secretName: {{ .Release.Name }}-web-tls
  rules:
  - host: {{ .Release.Name }}.{{ .Values.blockscout.domainName }}
    http:
      paths:
      -
        {{- if .Values.blockscout.web.suffix.enabled }}
        path: /({{ .Values.blockscout.web.suffix.path }})/(api/v1/(decompiled_smart_contract|verified_smart_contracts))
        {{ else }}
        path: /api/v1/(decompiled_smart_contract|verified_smart_contracts)
        {{- end }}
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-web
            port: 
              number: 4000
      -
        {{- if .Values.blockscout.web.suffix.enabled }}
        path: /({{ .Values.blockscout.web.suffix.path }})/((graphql|graphiql|api).*)
        {{ else }}
        path: /(graphql|graphiql|api)
        {{- end }}
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-api
            port: 
              number: 4000
      -
        {{- if .Values.blockscout.web.suffix.enabled }}
        path: /{{ .Values.blockscout.web.suffix.path }}(/|$)(.*)
        {{ else }}
        path: /
        {{- end }}
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-web
            port: 
              number: 4000
