{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1beta1" }}
apiVersion: networking.k8s.io/v1beta1
{{ else }}
apiVersion: extensions/v1beta1
{{ end -}}
kind: Ingress
metadata:
  name: {{ .Release.Name }}-web-ingress
  labels:
    {{- include "celo.blockscout.labels" . | nindent 4 }}
    component: blockscout-web-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 8m
    nginx.ingress.kubernetes.io/configuration-snippet: |
      location ~ /admin/.* {
        deny all;
      }
      location ~ /wobserver/.* {
        deny all;
      }
spec:
  tls:
  - hosts:
    - {{ .Release.Name }}.{{ .Values.domain.name }}.org
    secretName: {{ .Release.Name }}-web-tls
  rules:
  - host: {{ .Release.Name }}.{{ .Values.domain.name }}.org
    http:
      paths:
      - path: /api/v1/(decompiled_smart_contract|verified_smart_contracts)
        backend:
          serviceName: {{ .Release.Name }}-web
          servicePort: 4000
      - path: /(graphql|graphiql|api)
        backend:
          serviceName: {{ .Release.Name }}-api
          servicePort: 4000
      - path: /
        backend:
          serviceName: {{ .Release.Name }}-web
          servicePort: 4000
