apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-web-ingress
  labels:
    {{- include "celo.blockscout.labels" . | nindent 4 }}
    component: blockscout-web-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 8m
    nginx.ingress.kubernetes.io/configuration-snippet: |
      location ~ /admin/.* {
        deny all;
      }
      location ~ /wobserver/.* {
        deny all;
      }
      location ~ /address/(.*)/token_transfers {
        return 301 /address/$1/token-transfers;
      }
spec:
  rules:
  - host: {{ .Release.Name }}.{{ .Values.domain.name }}.org
    http:
      paths:
      - backend:
          service:
            name: {{ .Release.Name }}-web
            port:
              number: 4000
        path: /api/v1/(decompiled_smart_contract|verified_smart_contracts)
        pathType: ImplementationSpecific
      - backend:
          service:
            name: {{ .Release.Name }}-api
            port:
              number: 4000
        path: /(graphql|graphiql|api)
        pathType: ImplementationSpecific
      - backend:
          service:
            name: {{ .Release.Name }}-web
            port:
              number: 4000
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - {{ .Release.Name }}.{{ .Values.domain.name }}.org
    secretName: {{ .Release.Name }}-web-tls
