apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-api
  labels:
    {{- include "celo.blockscout.labels" . | nindent 4 }}
    component: blockscout-api
  annotations:
    {{- include "celo.blockscout.annotations" . | nindent 4 }}
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.blockscout.api.strategy.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.blockscout.api.strategy.rollingUpdate.maxUnavailable }}
  replicas: 1
  selector:
    matchLabels:
      app: blockscout
      release: {{ .Release.Name }}
      component: blockscout-api
  template:
    metadata:
      {{- if .Values.blockscout.metrics.enabled}}
      annotations:
        prometheus.io/path: /metrics/web
        prometheus.io/port: "4000"
        prometheus.io/scrape: "true"
      {{- end}}
      labels:
        app: blockscout
        release: {{ .Release.Name }}
        component: blockscout-api
    spec:
      serviceAccountName: {{ .Release.Name }}-rbac
      initContainers:
      - name: "blockscout-init"
        image: "groundnuty/k8s-wait-for:1.3"
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        args:
        - job
        - {{ .Release.Name }}-migration
      containers:
      - name: blockscout-api
        image: {{ .Values.blockscout.image.repository }}:api-{{ .Values.blockscout.image.tag }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        command:
        - /bin/sh
        - -c
        args:
        - |
           exec mix cmd --app block_scout_web "iex  --name {{ .Values.blockscout.api.erlangNodeName}}@0.0.0.0 -e 'IEx.configure(default_prompt: \"\", alive_prompt: \"\")' -S mix do deps.loadpaths --no-deps-check, phx.server --no-compile"
        ports:
        - name: http
          containerPort: {{ .Values.blockscout.api.port }}
        {{- if .Values.blockscout.api.readinessProbe.enabled }}
        readinessProbe:
          httpGet:
            path: /api/v1/health/liveness
            port: http
          initialDelaySeconds: {{ .Values.blockscout.api.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.blockscout.api.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.blockscout.api.readinessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.blockscout.api.readinessProbe.successThreshold }}
          failureThreshold: {{ .Values.blockscout.api.readinessProbe.failureThreshold }}
        {{- end }}
        {{- if .Values.blockscout.api.livenessProbe.enabled }}
        livenessProbe:
          httpGet:
            path: /api/v1/health/liveness
            port: http
          initialDelaySeconds: {{ .Values.blockscout.api.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.blockscout.api.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.blockscout.api.livenessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.blockscout.api.livenessProbe.successThreshold }}
          failureThreshold: {{ .Values.blockscout.api.livenessProbe.failureThreshold }}
        {{- end }}
        resources:
          requests:
            memory: {{ .Values.blockscout.api.resources.requests.memory }}
            cpu: {{ .Values.blockscout.api.resources.requests.cpu }}
        env:
        - name: DISABLE_WEBAPP
          value: "true"
        - name: DISABLE_WRITE_API
          value: "true"
        - name: DISABLE_INDEXER
          value: "true"
        - name: DISABLE_EXCHANGE_RATES
          value: "true"
        - name: POOL_SIZE
          value: {{ .Values.blockscout.api.pool_size | quote }}
        - name: BLOCKSCOUT_HOST
          value: {{ .Values.blockscout.web.host | quote }}
        - name: ENABLE_SOURCIFY_INTEGRATION
          value: {{ .Values.blockscout.web.sourcify.enabled | quote }}
        - name: SOURCIFY_SERVER_URL
          value: {{ .Values.blockscout.web.sourcify.serverUrl | quote }}
        - name: SOURCIFY_REPO_URL
          value: {{ .Values.blockscout.web.sourcify.repoUrl | quote }}
        - name: CHAIN_ID
          value: {{ .Values.blockscout.networkID | quote }}
{{ include "celo.blockscout-env-vars" . | indent 8 }}
{{- $data := dict "Values" .Values "DbSuffix" "-replica" "Database" .Values.blockscout.api.db }}
{{ include "celo.blockscout-db-sidecar" $data | indent 6 }}
{{ include "celo.blockscout-volumes" (dict "nfs_volumes" false "Release" .Release) | indent 6 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
