apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-web-ingress
  labels:
    app: blockscout
    chart: blockscout
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: blockscout-web-ingress
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/configuration-snippet: |
      location ~ /admin/.* {
        deny all;
      }
spec:
  tls:
  - hosts:
    - {{ .Release.Name }}.{{ .Values.domain.name }}.org
    secretName: {{ .Release.Name }}-web-tls
  rules:
  - host: {{ .Release.Name }}.{{ .Values.domain.name }}.org
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Release.Name }}-web
          servicePort: 4000
