nodeSelector: {}

# Expects cron schedule syntax
leaderboard:
  schedule: "*/5 * * * *"
  image:
    repository: us.gcr.io/celo-testnet/celo-monorepo
    tag: leaderboard-2708d6459b6efe2ab3ec04084d9c3819e202699f
  database: blockscout
  web3: https://baklava-forno.celo-testnet.org/
  sheet: 
  token: 
  credentials: 
  db:
    username:
    password:
    connection_name: 
