---
name: Build CircleCI related containers

on:
  push:
    paths:
      - 'dockerfiles/circleci/**'
    branches:
      - master
  pull_request:
    paths:
      - 'dockerfiles/circleci/**'
  workflow_dispatch:

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      geth: ${{ steps.changes.outputs.geth }}
      node12: ${{ steps.changes.outputs.node12 }}
      gcloud: ${{ steps.changes.outputs.gcloud }}
    steps:
      - uses: actions/checkout@v4
      - name: Check for changes
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            geth:
              - dockerfiles/circleci/Dockerfile
              - dockerfiles/circleci/.dockerignore
            node12:
              - dockerfiles/circleci/circleci-node12/Dockerfile
            gcloud:
              - dockerfiles/circleci/node10-gcloud/Dockerfile

  geth-build-dev:
    uses: celo-org/reusable-workflows/.github/workflows/container-cicd.yaml@v1.8
    name: Build us-west1-docker.pkg.dev/devopsre/dev-images/circleci-geth:testing
    needs: changes
    if: |
      needs.changes.outputs.geth == 'true' &&
      github.ref != 'refs/heads/master'
    with:
      workload-id-provider: projects/1094498259535/locations/global/workloadIdentityPools/gh-celo-monorepo/providers/github-by-repos
      service-account: 'celo-monorepo-dev@devopsre.iam.gserviceaccount.com'
      artifact-registry: us-west1-docker.pkg.dev/devopsre/dev-images/circleci-geth
      tag: testing
      context: dockerfiles/circleci
      trivy: true

  geth-build:
    uses: celo-org/reusable-workflows/.github/workflows/container-cicd.yaml@v1.8
    name: Build us-west1-docker.pkg.dev/devopsre/celo-monorepo/circleci-geth:latest
    needs: changes
    if: |
      needs.changes.outputs.geth == 'true' &&
      github.ref == 'refs/heads/master'
    with:
      workload-id-provider: projects/1094498259535/locations/global/workloadIdentityPools/gh-celo-monorepo-master/providers/github-by-repos
      service-account: 'celo-monorepo@devopsre.iam.gserviceaccount.com'
      artifact-registry: us-west1-docker.pkg.dev/devopsre/celo-monorepo/circleci-geth
      tag: latest
      context: dockerfiles/circleci
      trivy: true

  node12-build-dev:
    uses: celo-org/reusable-workflows/.github/workflows/container-cicd.yaml@v1.8
    name: Build us-west1-docker.pkg.dev/devopsre/dev-images/circleci-node12:testing
    needs: changes
    if: |
      needs.changes.outputs.node12 == 'true' &&
      github.ref != 'refs/heads/master'
    with:
      workload-id-provider: projects/1094498259535/locations/global/workloadIdentityPools/gh-celo-monorepo/providers/github-by-repos
      service-account: 'celo-monorepo-dev@devopsre.iam.gserviceaccount.com'
      artifact-registry: us-west1-docker.pkg.dev/devopsre/dev-images/circleci-node12
      tag: testing
      context: dockerfiles/circleci
      trivy: true

  node12-build:
    uses: celo-org/reusable-workflows/.github/workflows/container-cicd.yaml@v1.8
    name: Build us-west1-docker.pkg.dev/devopsre/celo-monorepo/circleci-node12:latest
    needs: changes
    if: |
      needs.changes.outputs.node12 == 'true' &&
      github.ref == 'refs/heads/master'
    with:
      workload-id-provider: projects/1094498259535/locations/global/workloadIdentityPools/gh-celo-monorepo-master/providers/github-by-repos
      service-account: 'celo-monorepo@devopsre.iam.gserviceaccount.com'
      artifact-registry: us-west1-docker.pkg.dev/devopsre/celo-monorepo/circleci-node12
      tag: latest
      context: dockerfiles/circleci
      trivy: true

