---
name: Build celocli container

on:
  push:
    paths:
      - 'dockerfiles/cli-standalone/**'
    branches:
      - master
  pull_request:
    paths:
      - 'dockerfiles/cli-standalone/**'
  workflow_dispatch:

jobs:
  celocli-build-dev:
    uses: celo-org/reusable-workflows/.github/workflows/container-cicd.yaml@v1.1
    name: Build us-west1-docker.pkg.dev/devopsre/dev-images/celocli:testing
    if: |
      github.ref != 'refs/heads/master'
    with:
      workload-id-provider: projects/1094498259535/locations/global/workloadIdentityPools/gh-celo-monorepo/providers/github-by-repos
      service-account: 'celo-monorepo-dev@devopsre.iam.gserviceaccount.com'
      artifact-registry: us-west1-docker.pkg.dev/devopsre/dev-images/celocli
      tag: testing
      context: .
      file: dockerfiles/cli-standalone/Dockerfile

  celocli-build:
    uses: celo-org/reusable-workflows/.github/workflows/container-cicd.yaml@v1.8
    name: Build us-west1-docker.pkg.dev/devopsre/celo-monorepo/celocli:latest
    if: |
      github.ref == 'refs/heads/master'
    with:
      workload-id-provider: projects/1094498259535/locations/global/workloadIdentityPools/gh-celo-monorepo-master/providers/github-by-repos
      service-account: 'celo-monorepo@devopsre.iam.gserviceaccount.com'
      artifact-registry: us-west1-docker.pkg.dev/devopsre/celo-monorepo/celocli
      tag: latest
      context: .
      file: dockerfiles/cli-standalone/Dockerfile
