---
name: Build celo-monorepo container

on:
  push:
    paths:
      - 'dockerfiles/celotool/**'
    branches:
      - master
  pull_request:
    paths:
      - 'dockerfiles/celotool/**'
  workflow_dispatch:

jobs:
  celotool-build-dev:
    uses: celo-org/reusable-workflows/.github/workflows/container-cicd.yaml@v1.8
    name: Build us-west1-docker.pkg.dev/devopsre/dev-images/celotool:testing
    if: |
      github.ref != 'refs/heads/master'
    with:
      workload-id-provider: projects/1094498259535/locations/global/workloadIdentityPools/gh-celo-monorepo/providers/github-by-repos
      service-account: 'celo-monorepo-dev@devopsre.iam.gserviceaccount.com'
      artifact-registry: us-west1-docker.pkg.dev/devopsre/dev-images/celotool
      tag: testing
      context: .
      file: dockerfiles/celotool/Dockerfile

  celotool-build:
    uses: celo-org/reusable-workflows/.github/workflows/container-cicd.yaml@v1.8
    name: Build us-west1-docker.pkg.dev/devopsre/celo-monorepo/celotool:latest
    if: |
      github.ref == 'refs/heads/master'
    with:
      workload-id-provider: projects/1094498259535/locations/global/workloadIdentityPools/gh-celo-monorepo-master/providers/github-by-repos
      service-account: 'celo-monorepo@devopsre.iam.gserviceaccount.com'
      artifact-registry: us-west1-docker.pkg.dev/devopsre/celo-monorepo/celotool
      tag: latest
      context: .
      file: dockerfiles/celotool/Dockerfile
