name: contracts-release

# on:
#   workflow_dispatch:
#     inputs:
#       release_version:
#         description: 'Version number of the release to be deployed'
#         required: true
#       network:
#         description: 'Network to deploy core contracts release on'
#         required: true

on: push
env:
  NETWORK: alfajores
  VERSION: 5
# env:
#   NETWORK: ${{ github.event.inputs.network }}
#   VERSION: ${{ github.event.inputs.release_version }}


jobs:
  core_contracts_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # all history

      - uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: yarn
        run: |
          npm install --global yarn
          yarn
          yarn lerna bootstrap

      - name: Build packages
        run: yarn lerna run build --ignore docs

      - name: Set up full node
        run: |
          export CELO_IMAGE=us.gcr.io/celo-org/geth:alfajores
          docker pull $CELO_IMAGE
          mkdir celo-data-dir
          cd celo-data-dir
          export CELO_ACCOUNT_ADDRESS=0x7F871c887e6a430D3c1F434737F568B07559F9E7
          docker run --name celo-fullnode -d --restart unless-stopped --stop-timeout 300 -p 127.0.0.1:8545:8545 -p 127.0.0.1:8546:8546 -p 30303:30303 -p 30303:30303/udp -v $PWD:/root/.celo $CELO_IMAGE --verbosity 3 --syncmode full --rpc --rpcaddr 0.0.0.0 --rpcapi eth,net,web3,debug,admin,personal --light.serve 90 --light.maxpeers 1000 --maxpeers 1100 --etherbase $CELO_ACCOUNT_ADDRESS --nousb --alfajores --datadir /root/.celo
          cd ..
      # - name: Setup lightest node
      #   if: ${{ env.NETWORK != 'staging' }}
      #   run: |
      #     export CELO_IMAGE=us.gcr.io/celo-org/geth:${{ env.NETWORK }}
      #     docker pull $CELO_IMAGE
      #     mkdir celo-data-dir
      #     cd celo-data-dir
      #     export NETWORK_OPTION="--${{ env.NETWORK }}"
      #     docker run --name celo-lightestnode -d --restart unless-stopped --stop-timeout 300 -p 127.0.0.1:8545:8545 -p 127.0.0.1:8546:8546 -p 30303:30303 -p 30303:30303/udp -v $PWD:/root/.celo $CELO_IMAGE --verbosity 3 --syncmode lightest --rpc --rpcaddr 0.0.0.0 --rpcapi eth,net,web3,debug,admin,personal --light.serve 90 --light.maxpeers 1000 --maxpeers 1100 --nousb $NETWORK_OPTION --datadir /root/.celo
      #     cd ..
      # - name: Checking if node is synced
      #   if: ${{ env.NETWORK != 'staging' }}
      #   run: |
      #     while true; do output=$(docker exec -i celo-lightestnode geth attach --exec "eth.syncing" | sed -r "s/\x1B\[([0-9]{1,3}(;[0-9]{1,2})?)?[mGK]//g"); echo $output; sleep 1; if [ $output == 'false' ]; then break; fi; done
      # - name: Setup node
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: '12'
      
      - name: Get branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: get_branch

      - name: Verify previous release
        run: |
          export OLD_BRANCH=core-contracts.v$((${{ env.VERSION }}-1))
          cd packages/protocol && yarn run verify-deployed -b $OLD_BRANCH -n ${{ env.NETWORK }} -f;

      - name: Verify version compatibility
        run: |
          OLD_BRANCH=core-contracts.v$((${{ env.VERSION }}-1))
          NEW_BRANCH=${{ steps.get_branch.outputs.branch }}
          cd packages/protocol && yarn run check-versions -a $OLD_BRANCH -b $NEW_BRANCH -r report.json;

      - name: Make release
        run: |
          export MNEMONIC='dinosaur tuna kiwi peasant spray receive jeans bubble city mention puzzle brother'
          NEW_BRANCH=${{ steps.get_branch.outputs.branch }}
          cd packages/protocol && yarn run make-release -b $NEW_BRANCH -f $MNEMONIC -n ${{ env.NETWORK }} -p proposal.json -r report.json -i ./releaseData/initializationData/release${{ env.VERSION }}.json -l libraries.json;
