---
name: Build celotool container

on:
  push:
    paths:
      - 'dockerfiles/celotool/**'
    branches:
      - master
  pull_request:
    paths:
      - 'dockerfiles/celotool/**'
  workflow_dispatch:

jobs:
  celotool-build-dev:
    uses: celo-org/reusable-workflows/.github/workflows/container-cicd.yaml@v1.13.1
    name: Build us-west1-docker.pkg.dev/devopsre/dev-images/celotool:${{ github.sha }}
    if: |
      github.ref != 'refs/heads/master'
    with:
      workload-id-provider: projects/1094498259535/locations/global/workloadIdentityPools/gh-celo-monorepo/providers/github-by-repos
      service-account: 'celo-monorepo-dev@devopsre.iam.gserviceaccount.com'
      access-token-lifetime: '360m'
      artifact-registry: us-west1-docker.pkg.dev/devopsre/dev-images/celotool
      tags: ${{ github.sha }}
      platforms: linux/amd64,linux/arm64
      context: .
      file: dockerfiles/celotool/Dockerfile
      trivy: true

  celotool-build:
    uses: celo-org/reusable-workflows/.github/workflows/container-cicd.yaml@v1.13.1
    name: Build us-west1-docker.pkg.dev/devopsre/celo-monorepo/celotool:${{ github.sha }}
    if: |
      github.ref == 'refs/heads/master'
    with:
      workload-id-provider: projects/1094498259535/locations/global/workloadIdentityPools/gh-celo-monorepo-master/providers/github-by-repos
      service-account: 'celo-monorepo@devopsre.iam.gserviceaccount.com'
      access-token-lifetime: '360m'
      artifact-registry: us-west1-docker.pkg.dev/devopsre/celo-monorepo/celotool
      tags: ${{ github.sha }}
      platforms: linux/amd64,linux/arm64
      context: .
      file: dockerfiles/celotool/Dockerfile
      trivy: true
